Add(DongGun): 피드백
modern-agile-team/6term-main-front pull request #65
Opened 2023-11-01 14:03 UTC by CBWDG

피드백 받을 내용의 PR입니다.

2023-11-02 10:24 UTC, soonki-98 commented on src/apis/chat-dummy/ChatFriendsDummy.ts
> +}
```suggestion
interface ChatMessage {
  chatId: string;
  textMessage: string;
  createdAt: string;
  sender: {
     id: string;
     name: string;
     profileImage: string;
  };
}

interface ChatMessageList {
   roomId: string;
   contents: ChatMessage[];
   hasNext: boolean;
}
```

2023-11-02 10:24 UTC, soonki-98 commented on src/apis/chat-dummy/ChatFriendsDummy.ts
> +}
타입은 이런식으로 누가 보냈는지에 대한 내용이 추가되는게 좋을거같아요

2023-11-02 10:24 UTC, soonki-98 commented on src/apis/chat-dummy/ChatFriendsDummy.ts
> +}
```suggestion
interface ChatRoom {
  roomId: string;
  userList: []{id: string; name: string;}; // 기타 유저 정보도 필요하면 포함
  hasNewMessage: : boolean;
}
```

2023-11-02 10:24 UTC, soonki-98 commented on src/apis/chat-dummy/ChatFriendsDummy.ts
> +}
추가로 채팅 메시지 리스트 타입도 있어야 할거같구요

2023-11-02 10:24 UTC, soonki-98 commented on src/components/organisms/chats/chat-modal/ChatModal.tsx
> +  }, []);
```suggestion
  const [isReadyToChat, setIsReadyToChat] = useState(false);
  const startChat= () => {
     const namespaceURL = 'http://13.209.21.62:3000/ch-653383a4468680bc4e9f8491';
    const socket = io(namespaceURL);

    socket.on('connect', () => {
      await // 채팅방 데이터 불러오는 api 호출
      setIsReadyToChat(true);
    });
    
  }
  useEffect(() => {
    startChat();
    return () => {
       leaveChat();
    }
  }, []);
```

2023-11-02 10:24 UTC, soonki-98 commented on src/components/organisms/chats/chatting/Chatting.tsx
```tsx
  useEffect((): any => {
    const scrollToBottom = () => {
      messageEnd.current?.scrollIntoView({ behavior: 'smooth' });
    };
    scrollToBottom();
  }, [messages]);
```
위 코드는 채팅방이 연결이 되었을때 실행이 되야하기 때문에 아래 형태로 바뀌는게 좋을거같아요.
```tsx
  // 이 기능은 내가 채팅을 쏘거나 받았을때 사용될 가능성이 있어서 useEffect 바깥으로 빼는게 좋을거같아요 
   const scrollToBottom = () => {
      messageEnd.current?.scrollIntoView({ behavior: 'smooth' });
    };

  useEffect((): any => {
    if (isReadyToChat) {
      scrollToBottom();
   }
      }, [isReadyToChat]);
```

2023-11-02 10:24 UTC, soonki-98 commented on src/components/organisms/chats/chatting/Chatting.tsx
```tsx
      const { ampm, hours, minutes } = timeStamp(new Date(Date.now()));
      const message = {
        // username: name,
        message: sendMessage,
        timestamp: `${ampm} ${hours}:${minutes}`,
        // roomId: roomId as string,
        // profileImage: profileImage,
      };
```
위 코드처럼 타임스탬프를 메시지 보낼때 텍스트로 변환하는게 아니라
```tsx 
      const message = {
        // username: name,
        message: sendMessage,
        timestamp: Date.now, // BE에 요청을 보낼때에는 timestamp를 그대로 보내고
        // roomId: roomId as string,
        // profileImage: profileImage,
      };
```

```tsx 
        // 여기 메시지 출력 영역에서 타임스탬프를 문자열로 반환하는게 좋을듯 합니다.
        {/* 채팅 메시지 출력 영역 */} 
        <Stack spacing={2} direction="column" sx={{ height: '350px' }}>
          <Paper
            variant="outlined"
            sx={{ overflow: 'auto', height: '500px', padding: '1rem' }}>
            {}
          </Paper>
        </Stack>
        {/* 채팅 메시지 입력 영역 */}
```

2023-11-02 10:24 UTC, soonki-98 commented on src/recoil/atoms/ChatAtom.ts
> +});
여기 아톰도 채팅방들을 관리하는 아톰과 개별 채팅방의 상태를 관리하는 아톰으로 관리되는게 어떨까 싶네요. <br/>
만약 한번에 여러개의 채팅방이 표시되는 구조가 아니라면 개별 채팅방 상태는 굳이 아톰으로 관리 안하고 useState로 관리해도 될듯요

2023-11-02 17:58 UTC, ssi02014 requested changes
구경하다 작은 코멘트 남겨봐용 :) ㅎㅎ

2023-11-02 17:58 UTC, ssi02014 commented on src/apis/friendApi/friendList.ts
> +};
`type alias` 말고 `interface`로 정의하면 어떨까요 :) 
다른 타입 정의한 것을보니 `interface`가 많이 보이네용 통일화되면 좋을 것 같아요
또한, 타입스크립트 팀은 공식적으로 `interface`를 권장하는 입장입니다.

https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

>For the most part, you can choose based on personal preference, and TypeScript will tell you if it needs something to be the other kind of declaration. If you would like a heuristic, use interface until you need to use features from type.

2023-11-02 17:58 UTC, ssi02014 commented on src/components/organisms/friend-list/styled.ts
> +`;
헉 컴포넌트인데 첫 글자가 소문자에용~

2023-11-02 17:58 UTC, ssi02014 commented on src/pages/mypage/index.tsx
> +const UserPage = (): React.JSX.Element => {
`JSX.Element`로 타입이 자동 추론 될거라 `React.JSX.Element` 굳이 안넣어주셔주도 됩니다 :)

2023-11-02 17:58 UTC, ssi02014 commented on src/components/organisms/chats/chat-modal/ChatModal.tsx
> +  }, []);
`namespaceURL`은 민감한 정보라고 판단되는데 환경변수(env)로 관리하면 어떨까유

2023-11-04 03:43 UTC, CBWDG commented on src/apis/chat-dummy/ChatFriendsDummy.ts
> +}
넵 타입 수정했습니다!!

2023-11-04 03:44 UTC, CBWDG commented on src/components/organisms/chats/chat-modal/ChatModal.tsx
> +  }, []);
env 파일에 따로 관리하겠습니다!!

2023-11-04 03:46 UTC, CBWDG commented on src/components/organisms/chats/chatting/Chatting.tsx
아 채팅 송수신 때 최신 메시지를 보여주기 위해 맨 밑으로 이동해야 하는 경우가 생길 수 있기 때문에
바깥으로 빼는 게 훨씬 효율적이겠군요 감사합니다!!

2023-11-04 03:47 UTC, CBWDG commented on src/components/organisms/chats/chatting/Chatting.tsx
넵 이해했습니다!!

2023-11-04 03:49 UTC, CBWDG commented on src/recoil/atoms/ChatAtom.ts
> +});
확실히 위의 코드처럼 애매하게 관리되는 것 보다
여러 채팅방들을 관리하는 아톰과 그 안에 개별 채팅방 하나하나의 상태를 관리하는 아톰으로 관리하는 쪽으로 수정해야 될 것 같습니다..

2023-11-04 03:49 UTC, CBWDG commented on src/apis/friendApi/friendList.ts
> +};
변경 완료했습니다!! 감사합니다 :)

2023-11-04 03:49 UTC, CBWDG commented on src/components/organisms/friend-list/styled.ts
> +`;
앗..

2023-11-04 03:53 UTC, CBWDG commented on src/pages/mypage/index.tsx
> +const UserPage = (): React.JSX.Element => {
오류를 따로 캡처해두진 않았는데, 현재 mypage/index.tsx가 mypage를 구성하는 최상단 컴포넌트입니다.
이제 하위 컴포넌트를 위 파일에서 return값으로 넣는 과정에서, 가끔씩 하위 컴포넌트에 빨간줄로 에러가 뜨면서
React.JSX.Element <- 이걸 명시해달라는 식의 오류가 발생합니다..
혹시 이건 어떤 문제일까요?

2023-11-04 08:24 UTC, ssi02014 commented on src/pages/mypage/index.tsx
> +const UserPage = (): React.JSX.Element => {
정확한 상황은 봐야겠지만 하위 컴포넌트가 JSX를 리턴하는지 확인해봐야겠네요!
아래와 같이 JSX를 리턴하는 경우에는 자동 타입추론됩니다!
```tsx
return (
  <></> 
);
// or
return (
  <div></div>
);
```

2023-11-04 08:25 UTC, ssi02014 commented
Pull Request 타이틀은 어떤 작업을 했는지 요약해서 작성하는게 좋습니다!
피드백이라는 타이틀은 어떤 작업을 했는지 파악이 힘들어요!

2023-11-07 01:05 UTC, zzzRYT approved these changes

2023-11-07 01:11 UTC, merged