Add(JaeJin/boardComment) : 댓글 기능 추가
modern-agile-team/6term-main-front pull request #69
Opened 2023-11-03 05:57 UTC by zzzRYT

2023-11-03 09:57 UTC, ssi02014 requested changes
지나가다 마이너한 코멘트 남깁니다 :)

2023-11-03 09:57 UTC, ssi02014 commented on src/components/organisms/post-unit/PostCreateComments.tsx
> +  const [getCreateInput, setCreateInput] = useState<string>('');
원시 타입은 `useState`가 초기값(initialState) 을 기반으로 알아서 타입 추론 해줄거라 굳이 제네릭으로 타입 지정 안하셔도 되요 ! 

```ts
function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>];
```

이펙티브 타입스크립트에서는 타입추론이 정확히 되고 있는데 과도하게 자세히 타입 지정을 하는건 오히려 코드 가독성을 떨어뜨린다고 언급하고 있습니다 😃

간단한 예로 굳이 아래와 같이 타입 지정 할 필요가 있을까요?
```ts
let str: string = "hi";
```

2023-11-03 09:57 UTC, ssi02014 commented on src/components/organisms/post-unit/PostCreateComments.tsx
> +    const res = USERS.getUserProfile;
호출을 안하고있는데 문제 없을까용? 😲

2023-11-04 00:17 UTC, zzzRYT commented on src/components/organisms/post-unit/PostCreateComments.tsx
> +    const res = USERS.getUserProfile;
아 아직 백엔드 로직이 구현되지 않은 부분이라 호출하지 않았습니다!!

2023-11-04 00:19 UTC, zzzRYT commented on src/components/organisms/post-unit/PostCreateComments.tsx
> +  const [getCreateInput, setCreateInput] = useState<string>('');
아하 조언 감사합니다!!

2023-11-06 12:04 UTC, CBWDG approved these changes
확인이 늦었습니다

2023-11-07 06:09 UTC, merged