Add(DongGun/requestFriend) : 친구 요청 확인, 수락, 리스트
modern-agile-team/6term-main-front pull request #73
Opened 2023-11-07 02:13 UTC by CBWDG

2023-11-07 14:02 UTC, ssi02014 requested changes
가볍게 리뷰드립니다 :) 
PR생성할 때 저를 리뷰어 등록해주셔도 좋아요

`src/apis/axiosInstance.ts`
`src/apis/user.ts `

위 두 파일 충돌나는거 한번 확인해보셔야 될 것 같아요

2023-11-07 14:02 UTC, ssi02014 commented on src/apis/friend-api/friendList.ts
> +      `${FRIENDS.path}/re sponses/pending`,
오타가 난 것 같아요 😄

2023-11-07 14:02 UTC, ssi02014 commented on src/apis/friend-api/friendList.ts
> +  async friendAccept(friend_id: number): Promise<AxiosResponse<Friend[]>> {
요청 데이터 포맷에 맞추려고 인자를 `friend_id(스네이크 케이스)`로 네이밍을 지은 것 같은데, 그럴 필요 없이 js에서는 그냥 `friendId(카멜 케이스)`로 네이밍을 지어주시는 것을 추천드립니다 😄

```ts
{
  friend_id: friendId
}
```

2023-11-07 14:02 UTC, ssi02014 commented on src/components/molecules/add-friend/AddFriend.tsx
> +import FRIENDS from '@/apis/friend-api/friendList';
이거 폴더 네이밍 변경한 이유가 따로 있나요? 저는 오히려 바꾸기 전이 나은 것 같네요 ..!
다른 폴더 네이밍들 보니 다 "-"로 구분되어 있는데 혹시 참고하신 레퍼런스 같은게 있으려나요 😂

2023-11-07 14:02 UTC, ssi02014 commented on src/components/organisms/chats/chatting/Chatting.tsx
> +            수정하고 해라!!!!!!!
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-11-07 14:04 UTC, CBWDG commented
아 넵!!! 감사합니다
pr은 미리 생성해둔거라 아직 작업한 내용은 거의 없습니당

2023-11-08 00:20 UTC, CBWDG commented on src/apis/friend-api/friendList.ts
> +      `${FRIENDS.path}/re sponses/pending`,
수정완료 했습니다!

2023-11-08 00:23 UTC, CBWDG commented on src/components/molecules/add-friend/AddFriend.tsx
> +import FRIENDS from '@/apis/friend-api/friendList';
초기에 설정한 폴더보다 폴더량이 너무 많아지니까 띄어쓰기가 필요하다고 느껴져 팀원과 `"-"` 로 구분하기로 했습니다!!
차라리 카멜케이스가 더 나을까요??

2023-11-08 00:28 UTC, ssi02014 commented on src/components/molecules/add-friend/AddFriend.tsx
> +import FRIENDS from '@/apis/friend-api/friendList';
아하 아니에요! 저도 여러개 찾아보니 여러 라이브러리들이 폴더명은 "-" 로 구분짓는 것을 꽤 발견했습니다! 팀 내에서 결정했다면 안바꿔도 될 것 같아요.

es) toss/slash, danggn/stackflow

2023-11-08 03:01 UTC, zzzRYT approved these changes

2023-11-08 16:33 UTC, ssi02014 commented on src/components/organisms/friend-list/ListRequested.tsx
> +        <S.UserBox key={index}>
key로 인덱스만을 넘겨주는 것은 최후의 수단이에요!
디테일하고 유니크한 값을 넘겨주는게 좋습니다 느낌이 id값이 적절해보이네요 :)

2023-11-09 01:35 UTC, CBWDG commented on src/components/organisms/friend-list/ListRequested.tsx
> +        <S.UserBox key={index}>
넵 알겠습니다!!

2023-11-10 05:36 UTC, zzzRYT approved these changes

2023-11-10 05:38 UTC, merged