Add(DongGun/ListResponse) : 친구요청 수락, 거절 기능 구현
modern-agile-team/6term-main-front pull request #85
Opened 2023-11-14 08:35 UTC by CBWDG

2023-11-14 12:18 UTC, zzzRYT approved these changes

2023-11-14 12:18 UTC, zzzRYT commented on src/apis/friend-api/friendList.ts
> +          friend_Id: friendId,
이거 오타인가요?

2023-11-14 14:19 UTC, ssi02014 requested changes
지나가다가 간단한 의견 남깁니다 :)

2023-11-14 14:19 UTC, ssi02014 commented on src/apis/friend-api/friendList.ts
> +          friend_Id: friendId,
오타맞겠쥬?
es6 부터 도입된 프로퍼티 축약 표현하면 더욱 깔끔하게 객체를 정의하실 수 있습니다 :) 
```js
{
  data: { freindId }
}
```

2023-11-14 14:19 UTC, ssi02014 commented on src/apis/friend-api/friendReject.ts
> +}
@zzzRYT @CBWDG 
이 data부분을 하나의 인터페이스로 분리하면 좋을 것 같아요 :) 
아래 예제는 단순 예시이고 네이밍은 더 명확하고 의미있는 것으로 고민해보면 좋을 것 같네요 😄

```tsx
export interface RejectFriendData {
  id: number;
  requesterId: number;
  respondentId: number;
  status: string;
  createdAt: string;
  requester: {
    name: string;
    userImage: {
      imageUrl: string;
    };
  };
}

export interface RejectFriend {
  data: RejectFriendData[]
}
```

또한, 이런 케이스가 많다면 제네릭을 활용한 공통의 타입을 정의하고 활용하는 것도 방법입니다

```ts
interface ResponseData<T> {
  data: T[]
}

export type RejectFriend = ResponseData<RejectFriendData>
```

2023-11-14 14:19 UTC, ssi02014 commented on src/components/molecules/chat-list/ChatDMFriendList.tsx
> +const DMFriendList: FC<DMFriendListProps> = () => {
@zzzRYT @CBWDG 
리액트 컴포넌트 타입으로 `FC(FunctionComponent)`는 지양합니다.
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/

실제로 CRA(Creact React App) 템플릿에서는 기본적으로 제공되는 FC가 제거되었습니다.
https://github.com/facebook/create-react-app/pull/8177

`DMFriendListProps` 때문이라면 차라리 필요할 때 해당 인터페이스를 생성해주세요

2023-11-14 14:19 UTC, ssi02014 commented on src/apis/friend-api/friendReject.ts
> +const REJECT = {
더 명확한 네이밍 없을까요? `REJECT`만으로는 의미가 명확하지 않은 것 같아요 😵

2023-11-14 14:19 UTC, ssi02014 commented on src/components/templates/relation-list/RelatioinLists.tsx
> +import RejectedList from '@/components/organisms/friend-list/ListRejected';
위 3가지 컴포넌트는 모두 네이밍을 더 의미있고, 명확하게 개선되면 좋을 것 같아요  👍
또한, 파일명(ex: ListResponsed)과 컴포넌트명(ex: ResponsedList)이 상이하네요

2023-11-15 01:48 UTC, CBWDG commented on src/apis/friend-api/friendList.ts
> +          friend_Id: friendId,
넵 알겠습니다!!

2023-11-15 01:49 UTC, CBWDG commented on src/apis/friend-api/friendReject.ts
> +}
이런 방법은 생각지도 못했네요 메모해두었다가 네이밍 고민해보고 리팩토링 시에 적용하겠습니다!!

2023-11-15 01:52 UTC, CBWDG commented on src/components/molecules/chat-list/ChatDMFriendList.tsx
> +const DMFriendList: FC<DMFriendListProps> = () => {
항상 VFC나 FC 사용을 염두할 때마다 움찔했는데, 지양하는 추세군요.. 다른 인터페이스 생성해서 적용하겠습니다.

2023-11-15 02:01 UTC, CBWDG commented on src/apis/friend-api/friendReject.ts
> +const REJECT = {
제가 알기론 Refuse보다 Reject가 훨씬 강력한 의사를 담은 거절로 알고 있어서 위와 같이 네이밍했는데, 확실히 좀 더 영구 거절이라는 의미를 담아야겠네요 ㅎㅎ..

2023-11-15 02:03 UTC, CBWDG commented on src/components/templates/relation-list/RelatioinLists.tsx
> +import RejectedList from '@/components/organisms/friend-list/ListRejected';
파일명과 컴포넌트명은 동일하도록 고치겠습니다!!
혹시 순서대로 요청받은목록, 요청보낸목록, 요청을 영구 거절한 목록(친구요청) 인데 네이밍 추천 부탁드려도될까요..? 제가 네이밍하려니 너무 길어질것 같습니다 ㅜ

2023-11-15 02:18 UTC, ssi02014 commented on src/apis/friend-api/friendReject.ts
> +const REJECT = {
좋은 네이밍이란 외부의 3자가 보더라도 이해할 수 있는 네이밍이라고 생각해요!

거절이라는 의미는 알겠는데 대체 "무엇을" 거절하는건지 히스토리를 모르는 사람 입장에서는 무엇을 거절하는건지 처음보면 확 와닿지가 않아요!

네이밍이 길어져도 상관없어요! 명확한 네이밍이 중요합니다😄 (실제로 메타에서는 함수명이 30자가 넘는 함수도 존재한다고해요)

아래 "차단목록"을 단순 예로 "(친구)차단목록" 이라고 생각이들고, 이는 rejectedFriendList 와 같은 네이밍이 더 의미있다고 느껴지는거에요!

또한, api를 요청해서 차단목록을 얻어오는거니(get) getRejectedFriendList 와 같은 네이밍이 훨씬 명확하다고 느껴집니다.

그런 의미에서 Reject 만으로는 부족하다고 느꼈어요

2023-11-15 02:19 UTC, ssi02014 commented on src/components/templates/relation-list/RelatioinLists.tsx
> +import RejectedList from '@/components/organisms/friend-list/ListRejected';
네이밍 길어져도 상관없어요! 무엇을 요청한 리스트인지, 응답받은 리스트인지 "무엇을"이 추가되면 좋을 것 같아요

2023-11-15 02:19 UTC, ssi02014 reviewed
추가 코멘트

2023-11-15 03:45 UTC, ssi02014 commented on src/components/molecules/chat-list/ChatDMFriendList.tsx
> +const DMFriendList: FC<DMFriendListProps> = () => {
단순 예제로 아래와 같이 props에 타입만 지정해줘도 충분합니다 :) 
```tsx
interface ComponentProps {
  arg1: number;
  arg2: string;
}

const Component = ({ arg1, arg2 }: ComponentProps) => {
  return (<div></div>);
}
```

2023-11-15 03:53 UTC, ssi02014 commented on src/apis/friend-api/friendReject.ts
> +  },
이것도 추가로 남기자면 차단 목록을 `GET`해오는건데 `reject (동사, 거절하다)`를 사용하는건 행위의 목적상 적절하지 않은 것 같습니다 😭 위에서도 남겼지만 `getRejectedFriendList`와 같은 네이밍은 어떨까요 🤔

2023-11-15 04:11 UTC, CBWDG commented on src/apis/friend-api/friendReject.ts
> +const REJECT = {
조언 감사합니다
차라리 길어지더라도 명확하게 인지할 수 있는 네이밍이 좀 더 좋다고 볼 수 있는 것이군요..
적극 반영하겠습니다!!

2023-11-15 04:11 UTC, CBWDG commented on src/apis/friend-api/friendReject.ts
> +  },
넵!!

2023-11-15 06:47 UTC, merged