Add(JaeJin/reComment) : 대댓글 기능 추가
modern-agile-team/6term-main-front pull request #86
Opened 2023-11-15 04:48 UTC by zzzRYT

아직 수정 중인 pr 입니다.

2023-11-15 10:16 UTC, ssi02014 requested changes
코멘트

2023-11-15 10:16 UTC, ssi02014 commented on src/apis/comments.ts
> +  },
`createReCommentApi` 처럼 어떤 행위에 대한 함수는 동사를 접두사로 붙여주는게 좋을 것 같아요 :)
해당 함수도 `deleteReCommentApi` 가 더 적절해보이고 좀 더 통일성 있어보이네요~!
아래 reCommentModifyApi도 동일합니다. 동사를 접두사로 붙여주세요 😊

아주 단순한 예로 useState에서 `"set"State` 와 같은거죠 동사인 set이 앞에 붙는 👍

2023-11-15 10:16 UTC, ssi02014 commented on src/components/molecules/post-comment/PostCreateReComment.tsx
> +  const [modifyReComment, setModifyReComment] = useState('');
`modifyReComment`는 동사가 "modify" 가 접두사로 붙어서 함수의 의미가 강한 것 같습니다~
input의 value로서 활용되니 `reCommentValue`는 어떨까요? 마찬가지로 setState도 `setReCommentValue`가 될 수 있을 것 같아요!
아니면 수정 된 댓글 값이라는 의미의 `modifiedReCommentValue` 도 나쁘지 않을 것 같네요

2023-11-15 10:16 UTC, ssi02014 commented on src/components/molecules/post-comment/PostCreateReComment.tsx
> +}
@zzzRYT @CBWDG 
특정 컴포넌트의 Props의 타입의 네이밍은 `{componentName}Props` 가 어떨까요? 여러 레퍼런스들을 참고해도 해당 네이밍 컨벤션을 사용하시는분들이 꽤 많습니다 (ex: 벨로퍼트)
팀 내에서 규칙을 잡고 네이밍을 통일성있게 잡아주면 좋을 것 같습니다. 즉, `PostCreateReCommentProps`가 적절해보입니다.

### reference
https://stackoverflow.com/questions/65638991/interface-naming-convention-interface-name-clashes-with-component-name

2023-11-15 10:16 UTC, ssi02014 commented on src/components/molecules/post-comment/PostReComment.tsx
> +}
여기서는 `ReCommentInfo` 네이밍으로 작성되어 있네요 
상단의 코멘트(PropsCommentType)와 비슷한 이유입니다 개선되면 좋을 것 같아요!

2023-11-15 10:16 UTC, ssi02014 commented on src/components/templates/post-unit-temp/PostUnitTemplate.tsx
> +  reComment: [];
타입이 그냥 배열이에요! `string[]`, `number[]`,  `{type}[]`뭐 이런식으로 정의되어야 할 것 같아요!

2023-11-15 10:16 UTC, ssi02014 commented on src/components/molecules/post-comment/PostReComment.tsx
> +  const [modifyReComment, setModifyReComment] = useState(reComment.content);
22222

2023-11-16 12:24 UTC, CBWDG approved these changes

2023-11-17 05:44 UTC, CBWDG approved these changes

2023-11-17 05:45 UTC, merged