Add(DongGun/FriendList) : 친구 기능 수정, Recoil로 관리
modern-agile-team/6term-main-front pull request #93
Opened 2023-11-16 12:14 UTC by CBWDG

아직 완료된 작업은 아닙니다 !!
설계 단계에서 요청할 값과 타입을 제대로 명시하지 않고 시작해서 그런지
query문으로 받은 UserId : number와 친구요청 보낸 사용자의 Id인 requesterId : number를 비교해서 친구 목록을 구성해야 하는 점이 너무 어렵고 복잡하네요...

2023-11-16 12:18 UTC, zzzRYT approved these changes

2023-11-16 14:08 UTC, ssi02014 requested changes
리뷰드립니다 :)

2023-11-16 14:08 UTC, ssi02014 commented on src/components/organisms/friend-list/ListFriend.tsx
> +      });
비~~슷한 코드들이 반복되는 느낌이에요 이 부분 어떻게 개선하면 좋을까요? 🤔
아래 예제처럼 `getUserType` 함수를 분리하고, `객체 대괄호 접근법`으로 관리하면 조금 더 깔끔해지고 가독성을 높일 수 있을 것 같아요 😄
또한, map은 새로운 배열을 반환해주기 때문에 `updatedFriendInfoList` 라고 네이밍을 지어봤어요
간단한 아이디어이니 참고해보시고 타입은 제가 정확히 몰라서 작성하지 않았으니 감안해주세요
네이밍도 조금 더 적절한게 무엇일까 고민해보면 좋을 것 같네요 😄
```suggestion
const getUserType = (loginUserId, requesterId) => {
  const isCurrentUserRequester = loginUserId === requesterId;

  return {
    requester: isCurrentUserRequester ? "requester" : "respondent",
    respondent: isCurrentUserRequester ? "respondent" : "requester",
  };
};

const updatedFriendInfoList = response.map((item) => {
  const { requester, respondent } = getUserType(loginUserId, item.requesterId);

  return {
    requesterId: item[`${requester}Id`],
    requesterName: item[requester]?.name || "",
    requesterImage: item[requester]?.userImage?.imageUrl || "",
    respondentId: item[`${respondent}Id`],
    respondentName: item[respondent]?.name || "",
    respondentImage: item[respondent]?.userImage?.imageUrl || "",
  };
});
```

2023-11-17 06:27 UTC, soonki-98 commented on src/components/organisms/friend-list/ListFriend.tsx
> +    : undefined;
로그인한 유저의 아이디 정보를 router에 저장하고 있는건가요?

2023-11-17 06:30 UTC, soonki-98 commented on src/components/organisms/friend-list/ListFriend.tsx
> +          : friendToDelete?.requesterName
이 변수가 아래에서도 다시 사용되고 있는데 idToDelete 변수를 위에서 선언하고 가져다 쓰는게 나을거 같네요

2023-11-17 06:32 UTC, soonki-98 commented on src/components/organisms/friend-list/ListFriend.tsx
> +        friend.respondentId === deletedId || friend.requesterId === deletedId,
repondent랑 requester는 어떤 차이에요?

2023-11-21 07:32 UTC, merged